# Configuration for deploying puppet master/agents automatically using stephenrjohnson-puppet (common to both dev and hardware cloud).

autopuppet::master::reports: 'store, http'
autopuppet::master::clientclean: false

# enable directory environments
autopuppet::master::environments: 'directory'
autopuppet::master::masterenv:
  'production':
    modulepath: '/opt/puppet-modules/'
    manifest: '/etc/puppet/manifests/'

# dashboard broken with ubuntu-14
#  puppet-dashboard : Depends: ruby1.8 (>= 1.8.7) which is a virtual package.
#                      Depends: rubygems which is a virtual package.
autopuppet::dashboard::enable: false
autopuppet::master::reporturl: "http://%{hiera('autopuppet::common::puppet_master')}:3000/reports/upload"

puppetdb::java_args:
  '-Xmx': '512m'
  '-Xms': '256m'
