sys11sensu::rabbitmq_host: localhost
sys11sensu::rabbitmq_user: sensu
sys11sensu::rabbitmq_password: sensu_rabbitmq_password
sys11sensu::rabbitmq_vhost: sensu
sys11sensu::uchiwa_version: 0.10.1-1

# Handlers disabled, since they all need to be configured on a per-project basis
# sys11sensu::profile::server::handlers::default_handlers:
#  - hipchat
#  - mailer

# sensu common stuff
sensu::client_keepalive:
  'thresholds':
    warning: 180
    critical: 300

# Example configuration for email notifications (you'll need to provide sensible
# values to use this)

#sys11sensu::profile::server::handlers::mailer::settings:
#  admin_gui: "http://%{openstack_floating_ip}:3001"
#  mail_from: 'changeme@no.such.domain.invalid'
#  mail_to: 'changeme@no.such.domain.invalid'
#  smtp_port: '25'
#  smtp_domain: 'no.such.domain.invalid'

# Example configuration for hipchat notifications (you'll need to provide sensible
# values to use this)

#sys11sensu::profile::server::handlers::hipchat::settings:
#    apikey: '12345678' # Insert your API key here
#    apiversion: 'v2'
#    room: 'sensu-alerts'
#    from: 'Sensu'
